# Generated by Django 5.0.6 on 2024-05-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
