# Generated by Django 5.0.6 on 2024-05-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_answer_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='points',
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
