# Generated by Django 5.0.6 on 2024-05-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_penalty_options'),
        ('courses', '0004_lesson_completed_by_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='lesson',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='courses.lesson'),
        ),
    ]
