# Generated by Django 5.0.6 on 2024-05-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_assessment_completed_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set(),
        ),
    ]
