# Generated by Django 5.0.6 on 2024-06-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assessment_time_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='time_taken',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
